// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkopUBAdntYhCD520Zso_NafAssrMCVsQ',
    appId: '1:423856718799:web:591e8f8a7b395b382688ba',
    messagingSenderId: '423856718799',
    projectId: 'fool-proof-attendance-app',
    authDomain: 'fool-proof-attendance-app.firebaseapp.com',
    storageBucket: 'fool-proof-attendance-app.firebasestorage.app',
    measurementId: 'G-8DK4T9LTP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9CfEH9soM47vJ-QhPIIGIILyz9SgTuY',
    appId: '1:423856718799:android:bc19eea3f44d4fdf2688ba',
    messagingSenderId: '423856718799',
    projectId: 'fool-proof-attendance-app',
    storageBucket: 'fool-proof-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHzAGJBb8Wrefdqpid__IP147_jOAVZ8',
    appId: '1:423856718799:ios:2d61f7fcdfe12c852688ba',
    messagingSenderId: '423856718799',
    projectId: 'fool-proof-attendance-app',
    storageBucket: 'fool-proof-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnHzAGJBb8Wrefdqpid__IP147_jOAVZ8',
    appId: '1:423856718799:ios:2d61f7fcdfe12c852688ba',
    messagingSenderId: '423856718799',
    projectId: 'fool-proof-attendance-app',
    storageBucket: 'fool-proof-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkopUBAdntYhCD520Zso_NafAssrMCVsQ',
    appId: '1:423856718799:web:9c76f8e9e7b2c49b2688ba',
    messagingSenderId: '423856718799',
    projectId: 'fool-proof-attendance-app',
    authDomain: 'fool-proof-attendance-app.firebaseapp.com',
    storageBucket: 'fool-proof-attendance-app.firebasestorage.app',
    measurementId: 'G-MQ2TRGTYC2',
  );
}
